Repository andela/ah-frontend-prime, pull requests merged in 2019-05, with the labels that each got.

#5 #164798247 Setup React Router version 4
  package.json
  src/components/home.js
  src/components/loginComponent.js
  src/components/routes.js
  src/containers/app.js
  src/index.js
  tests/__snapshots__/app.test.js.snap
  tests/app.test.js
  webpack.config.js
Labels: finished

#6 #164798241 Hound<>Github Integration
  .eslintignore
  .eslintrc.json
  .hound.yml
  package.json
Labels: finished, review ready

#7 #165716752 Setup Authors Heaven for Heroku deployment
  Procfile
  dist/index.html
  dist/index_bundle.js
  package.json
  server.js
  src/styles/app.scss
Labels: finished

#10 #164798249 Codeclimate test coverage
  .circleci/config.yml
  .travis.yml
  README.md
Labels: finished, review ready

#11 #165819922 Implement Landing Page
  .gitignore
  .travis.yml
  dist/index.html
  dist/index_bundle.js
  jest.config.js
  package.json
  src/SetupTests.js
  src/actions/getArticles.js
  src/actions/types.js
  src/components/header.js
  src/components/home.js
  src/components/routes.js
  src/containers/app.js
  src/index.html
  src/index.js
  src/reducers/getArticlesReducer.js
  src/reducers/rootReducer.js
  src/styles/app.scss
  src/tests/__snapshots__/app.test.js.snap
  src/tests/actions/getArticlesAction.test.js
  src/tests/app.test.js
  src/tests/mock_data/moxios_mock.js
  src/tests/reducers/getArticlesReducer.test.js
  tests/__snapshots__/app.test.js.snap
  tests/app.test.js
Labels: TTL review ready, finished

#13 #164798253 User should be able to login
  .babelrc
  .eslintignore
  .eslintrc.json
  .gitignore
  .hound.yml
  app.json
  package.json
  server.js
  src/actions/LoginAction.js
  src/actions/types.js
  src/components/header.js
  src/components/login/LoginModal.js
  src/components/loginComponent.js
  src/components/routes.js
  src/containers/Login/LoginContainer.js
  src/containers/app.js
  src/index.html
  src/index.scss
  src/reducers/loginReducer.js
  src/reducers/rootReducer.js
  src/store.js
  src/styles/app.scss
  src/styles/register.scss
  src/tests/__snapshots__/app.test.js.snap
  src/tests/actions/LoginAction.test.js
  src/tests/actions/getArticlesAction.test.js
  src/tests/app.test.js
  src/tests/components/__snapshots__/loginModal.test.js.snap
  src/tests/components/loginModal.test.js
  src/tests/containers/LoginContainer.test.js
  src/tests/containers/__snapshots__/LoginContainer.test.js.snap
  src/tests/mock_data/moxios_mock.js
  src/tests/reducers/loginReducer.test.js
  webpack.config.js
Labels: TTL review ready, finished

#14 #164798250 Users should be able to register.
  .babelrc
  .eslintrc.json
  app.json
  dist/index_bundle.js
  package.json
  src/actions/LoginAction.js
  src/actions/registerActions.js
  src/actions/types.js
  src/components/registerComponent.js
  src/components/routes.js
  src/containers/Login/LoginContainer.js
  src/containers/app.js
  src/containers/registerContainer.js
  src/index.html
  src/index.js
  src/reducers/authReducer.js
  src/reducers/loginReducer.js
  src/reducers/rootReducer.js
  src/store.js
  src/styles/app.scss
  src/styles/images/facebook.png
  src/styles/register.scss
  src/tests/actions/authActions.test.js
  src/tests/components/__snapshots__/registerComponent.test.js.snap
  src/tests/components/registerComponent.test.js
  src/tests/containers/LoginContainer.test.js
  src/tests/containers/__snapshots__/registerContainer.test.js.snap
  src/tests/containers/registerContainer.test.js
  src/tests/reducers/authReducer.test.js
  src/utils/regex.js
  src/utils/validateforms.js
  webpack.config.js
Labels: TTL review ready, finished

#12 #164798254 Social-authentication using google and facebook
  package.json
  src/actions/SocialAuthActions.js
  src/actions/types.js
  src/components/SocialAuth.js
  src/components/login/LoginModal.js
  src/components/registerComponent.js
  src/components/routes.js
  src/config.json
  src/containers/SocialAuthContainer.js
  src/containers/app.js
  src/index.html
  src/reducers/rootReducer.js
  src/reducers/socialAuthReducer.js
  src/styles/register.scss
  src/tests/SocialAuth/SocialAuthActions.spec.js
  src/tests/SocialAuth/SocialAuthComponent.spec.js
  src/tests/SocialAuth/SocialAuthContainer.spec.js
  src/tests/SocialAuth/SocialAuthReducer.spec.js
  src/tests/SocialAuth/__snapshots__/SocialAuthComponent.spec.js.snap
  src/tests/SocialAuth/__snapshots__/SocialAuthContainer.spec.js.snap
  src/tests/__snapshots__/app.test.js.snap
  src/tests/app.test.js
  src/tests/mock_data/moxios_mock.js
  src/urls.js
Labels: TTL review ready

#17 164798252 users should be able to reset their passwords
  package.json
  src/actions/passwordResetActions.js
  src/actions/registerActions.js
  src/actions/types.js
  src/components/SocialAuth.js
  src/components/home.js
  src/components/login/LoginModal.js
  src/components/navbar.js
  src/components/passwordReset.js
  src/components/passwordResetEmail.js
  src/components/routes.js
  src/components/sideDrawer.js
  src/containers/passwordReset.js
  src/containers/passwordResetEmail.js
  src/containers/registerContainer.js
  src/index.html
  src/index.js
  src/reducers/authReducer.js
  src/reducers/passwordChangeReducer.js
  src/reducers/passwordResetReducer.js
  src/reducers/rootReducer.js
  src/styles/app.scss
  src/styles/images/icons8-bell-100.png
  src/styles/navbar.scss
  src/styles/passwordreset.scss
  src/styles/register.scss
  src/styles/sidedrawer.scss
  src/tests/__snapshots__/app.test.js.snap
  src/tests/actions/authActions.test.js
  src/tests/actions/passwordResetActions.test.js
  src/tests/components/__snapshots__/navbar.test.js.snap
  src/tests/components/__snapshots__/passwordReset.test.js.snap
  src/tests/components/__snapshots__/passwordResetEmail.test.js.snap
  src/tests/components/__snapshots__/sideBar.test.js.snap
  src/tests/components/navbar.test.js
  src/tests/components/passwordReset.test.js
  src/tests/components/passwordResetEmail.test.js
  src/tests/components/sideBar.test.js
  src/tests/containers/__snapshots__/passwordResetContainer.test.js.snap
  src/tests/containers/__snapshots__/passwordResetEmailContainer.test.js.snap
  src/tests/containers/passwordResetContainer.test.js
  src/tests/containers/passwordResetEmailContainer.test.js
  src/tests/reducers/authReducer.test.js
  src/tests/reducers/passwordChangeReducer.test.js
  src/tests/reducers/passwordResetReducer.test.js
  webpack.config.js
Labels: finished

#16 #164798255 Enable users to view and edit their profiles
  .gitignore
  package.json
  src/actions/LoginAction.js
  src/actions/SocialAuthActions.js
  src/actions/profileActions.js
  src/actions/types.js
  src/components/header.js
  src/components/navbar.js
  src/components/routes.js
  src/components/userProfile/EditProfile.js
  src/components/userProfile/ProfileComponent.js
  src/components/userProfile/ProfilePage.js
  src/containers/SocialAuthContainer.js
  src/containers/profile/EditProfileContainer.js
  src/containers/profile/ProfileContainer.js
  src/firebase/config.js
  src/index.html
  src/index.js
  src/reducers/profileReducer.js
  src/reducers/rootReducer.js
  src/reducers/socialAuthReducer.js
  src/styles/app.scss
  src/styles/images/profile.jpeg
  src/styles/navbar.scss
  src/styles/profile.scss
  src/styles/sidedrawer.scss
  src/tests/SocialAuth/SocialAuthReducer.spec.js
  src/tests/actions/profileAction.test.js
  src/tests/components/EditProfile.test.js
  src/tests/components/ProfileComponent.test.js
  src/tests/components/ProfilePage.test.js
  src/tests/components/__snapshots__/EditProfile.test.js.snap
  src/tests/components/__snapshots__/ProfileComponent.test.js.snap
  src/tests/components/__snapshots__/ProfilePage.test.js.snap
  src/tests/components/__snapshots__/navbar.test.js.snap
  src/tests/components/__snapshots__/passwordReset.test.js.snap
  src/tests/components/__snapshots__/passwordResetEmail.test.js.snap
  src/tests/components/navbar.test.js
  src/tests/containers/ProfileContainer.test.js
  src/tests/containers/__snapshots__/ProfileContainer.test.js.snap
  src/tests/reducers/profileReducer.test.js
  webpack.config.js
Labels: TTL review ready

#18 #164798263 Users can follow and unfollow each other
  package.json
  src/actions/SocialAuthActions.js
  src/actions/getArticle.js
  src/actions/profileActions.js
  src/actions/types.js
  src/components/FollowersList.js
  src/components/FollowingList.js
  src/components/FollowsButton.js
  src/components/FollowsStats.js
  src/components/articles/createArticlePage.js
  src/components/articles/singleArticle.js
  src/components/navbar.js
  src/components/routes.js
  src/components/userProfile/EditProfile.js
  src/components/userProfile/ProfileComponent.js
  src/components/userProfile/ProfilePage.js
  src/containers/profile/ProfileContainer.js
  src/containers/profile/UsersProfileContainer.js
  src/index.html
  src/reducers/followsUnfollowsReducer.js
  src/reducers/profileReducer.js
  src/reducers/rootReducer.js
  src/styles/app.scss
  src/styles/profile.scss
  src/styles/register.scss
  src/tests/SocialAuth/__snapshots__/SocialAuthComponent.spec.js.snap
  src/tests/SocialAuth/__snapshots__/SocialAuthContainer.spec.js.snap
  src/tests/__snapshots__/app.test.js.snap
  src/tests/actions/createArticleAction.test.js
  src/tests/actions/getArticleAction.test.js
  src/tests/actions/profileAction.test.js
  src/tests/app.test.js
  src/tests/components/EditProfile.test.js
  src/tests/components/ProfileComponent.test.js
  src/tests/components/__snapshots__/EditProfile.test.js.snap
  src/tests/components/__snapshots__/ProfileComponent.test.js.snap
  src/tests/components/__snapshots__/ProfilePage.test.js.snap
  src/tests/components/__snapshots__/articles.test.js.snap
  src/tests/components/__snapshots__/followUnfollowComponents.test.js.snap
  src/tests/components/__snapshots__/loginModal.test.js.snap
  src/tests/components/__snapshots__/navbar.test.js.snap
  src/tests/components/__snapshots__/passwordReset.test.js.snap
  src/tests/components/__snapshots__/passwordResetEmail.test.js.snap
  src/tests/components/__snapshots__/registerComponent.test.js.snap
  src/tests/components/__snapshots__/sideBar.test.js.snap
  src/tests/components/__snapshots__/userArticles.test.js.snap
  src/tests/components/followUnfollowComponents.test.js
  src/tests/components/singleArticle.test.js
  src/tests/containers/ProfileContainer.test.js
  src/tests/containers/__snapshots__/LoginContainer.test.js.snap
  src/tests/containers/__snapshots__/ProfileContainer.test.js.snap
  src/tests/containers/__snapshots__/passwordResetContainer.test.js.snap
  src/tests/containers/__snapshots__/passwordResetEmailContainer.test.js.snap
  src/tests/containers/__snapshots__/registerContainer.test.js.snap
  src/tests/containers/articleContainer.test.js
  src/tests/mock_data/moxios_mock.js
  src/tests/reducers/profileReducer.test.js
Labels: TTL review ready

#19 #164798259 Pagination support for articles
  src/actions/getArticles.js
  src/components/home.js
  src/reducers/getArticlesReducer.js
  src/tests/__snapshots__/app.test.js.snap
  src/tests/actions/getArticlesAction.test.js
  src/tests/components/articles.test.js
  src/tests/mock_data/moxios_mock.js
  src/tests/reducers/getArticlesReducer.test.js
Labels: TTL review ready, finished

#20 #164798260 Users can like or dislike articles
  src/actions/LikeDislikeActions.js
  src/actions/types.js
  src/components/articles/singleArticle.js
  src/reducers/getArticleReducer.js
  src/styles/images/dislike.png
  src/styles/images/like.png
  src/styles/profile.scss
  src/tests/actions/LikeDislikeActions.test.js
  src/tests/components/__snapshots__/singleArticle.test.js.snap
  src/tests/components/singleArticle.test.js
  src/tests/reducers/getArticleReducer.test.js
Labels: TTL review ready

#22 #164798258 Users should be able to comment on articles.
  package.json
  src/actions/commentsActions.js
  src/actions/types.js
  src/components/articles/singleArticle.js
  src/components/comments.js
  src/components/sideDrawer.js
  src/containers/profile/UsersProfileContainer.js
  src/reducers/commentsReducer.js
  src/reducers/getCommentsReducer.js
  src/reducers/rootReducer.js
  src/styles/comments.scss
  src/styles/singleArticle.scss
  src/tests/actions/commentsActions.test.js
  src/tests/components/__snapshots__/comments.test.js.snap
  src/tests/components/comments.test.js
  src/tests/mock_data/moxios_mock.js
  src/tests/reducers/comentsReducer.test.js
  src/tests/reducers/getCommentsReducer.test.js
Labels: finished, review ready
